version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lars-testing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l3q8v1qjqtq2"
s3_prefix = "lars-testing"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
